apiVersion: v1
kind: Service
metadata:
  name: git-server
  namespace: git-server
spec:
  selector:
    app: git-server
  ports:
    - name: git
      port: 9418
      targetPort: 9418
      protocol: TCP
  type: ClusterIP
