---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-registrar
  namespace: {{ .Values.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vcluster-secret-reader
  namespace: {{ .Values.name }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vc-vcluster"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcluster-secret-reader
  namespace: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: vcluster-registrar
    namespace: {{ .Values.name }}
roleRef:
  kind: Role
  name: vcluster-secret-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-cluster-secret-writer-{{ .Values.name }}
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-cluster-registrar
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: vcluster-registrar
    namespace: {{ .Values.name }}
roleRef:
  kind: Role
  name: argocd-cluster-secret-writer-{{ .Values.name }}
  apiGroup: rbac.authorization.k8s.io
